version: "3.9"
services:
  
  shacl-runner:
    build: 
      context: backend/
    ports:
      - "6777:6777"
      - "9229:9229"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./build/:/usr/src/app/build/
    network_mode: host

  
  # ontop-cli:
  #   image: ontop/ontop-endpoint
  #   environment:
  #     ONTOP_ONTOLOGY_FILE: /opt/ontop/prototyp/prototyp.owl
  #     ONTOP_MAPPING_FILE: /opt/ontop/prototyp/prototyp.obda
  #     ONTOP_PROPERTIES_FILE: /opt/ontop/connection/connection.properties
  #     ONTOP_CORS_ALLOWED_ORIGINS: "*"
  #     ONTOP_DEV_MODE: "true"
  #     ONTOP_LAZY_INIT: "true"
  #   volumes:
  #     - ./ontop-cli/smadi_prototyp:/opt/ontop/prototyp:ro
  #     - ./ontop-cli/connection/:/opt/ontop/connection:ro
  #     - ./ontop-cli/jdbc:/opt/ontop/jdbc:ro
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - gardens
  # comunica:
  #   build: comunica/
  #   volumes:
  #     - ./ontop-cli/prototyp:/usr/comunica/prototyp/
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - gardens
  
  shacl-frontend:
    environment:
      - REACT_APP_BACKEND_URL="localhost/shacl-runner-api/"
    build:
      context: frontend/
    ports:
      - "3000:3000"
    networks:
      - porch
    profiles:
      - full
    depends_on:
      - shacl-runner


networks:
  # The frontend only connects to the Node.js runner via the porch network
  porch:
  # All internal communications happen in the gardens
  gardens:
