

# Target Query
SELECT ?x WHERE {
    ?x a :Parameter.

    SELECT ?x WHERE {
        ?x a :Kristallstruktur.
    }
    
}

# Cardinality Query
minCount 1 hatParameter class K
7
SELECT ?x WHERE {
    ?x a :Parameter.

    SELECT ?x WHERE {
        ?x :hat_Parameter ?p
    }
    
}

SELECT DISTINCT ?x ?p WHERE {
    ?x a <urn:absolute/prototyp#physikalische_Groesse>.
    {
        SELECT DISTINCT * WHERE {
        { 
            { 
                { ?x <urn:absolute/prototyp#A> ?p. }
                UNION
                { ?x <urn:absolute/prototyp#B> ?p.}
            }
            UNION
            { ?x <urn:absolute/prototyp#C> ?p.}
        }
        UNION
        { ?x <urn:absolute/prototyp#D> ?p.}

    }
}