# Anfrage 1

SELECT DISTINCT ?X, ?Y, ?Z, ?W WHERE {
    # 1. Targetdefinition
    ?X a :Material;

    # 2. PSHAPE 1
    #   1. Pfad
    ?X :hat_Parameter ?Y;
    #   2. Constraints
    ?x a 
    


};

 SELECT DISTINCT * () {
    ?target a :Gitterkonstante_a;
            ^:hat_Parameter ?a .
    
    ?a  a :MSM-Material;
    OPTIONAL {
        ?a :hat_Parameter ?b;
        ?b a :Gitterkonstante_b;
        FILTER(?b == 12)
    }
    BIND (EXISTS(?a :hat_Parameter ?b) AS ?exists)
 } GROUP BY ?target ?a